# Generated by Django 3.0.3 on 2020-03-02 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='last_water',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='plants',
            name='next_water',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='plants',
            name='water_every',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='plants',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
