# Generated by Django 3.0.3 on 2020-03-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200302_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='user',
        ),
    ]
