# Generated by Django 3.0.3 on 2020-03-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200315_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='next_water',
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(blank=True, upload_to='plant_pics'),
        ),
    ]
