# Generated by Django 3.0.3 on 2020-03-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_plants_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='plant_image',
        ),
    ]
