# Generated by Django 3.0.3 on 2020-03-18 22:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0006_plant_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('owner', 'slug')},
        ),
    ]
