# Generated by Django 3.0.3 on 2020-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200318_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(blank=True, upload_to='media/plant_pics'),
        ),
    ]
