# Generated by Django 3.0.4 on 2020-03-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20200320_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='water_now',
            field=models.BooleanField(default=False),
        ),
    ]
