# Generated by Django 3.0.4 on 2020-03-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_plant_water_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['location']},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='water_now',
        ),
    ]
