# Generated by Django 3.0.4 on 2020-03-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20200322_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
