# Generated by Django 3.0.4 on 2020-03-23 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0012_auto_20200323_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('owner', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('owner', 'name')},
        ),
    ]
