# Generated by Django 3.0.4 on 2020-03-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20200323_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
    ]
