# Generated by Django 3.0.4 on 2020-03-27 19:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20200323_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilize_every',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_fertilize',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
