# Generated by Django 3.0.4 on 2020-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20200327_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['room'], 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['location'], 'verbose_name': 'plant', 'verbose_name_plural': 'plants'},
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(max_length=50, verbose_name='room'),
        ),
    ]
