# Generated by Django 3.0.4 on 2020-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20200409_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
