# Generated by Django 3.0.4 on 2020-04-10 11:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20200409_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(max_length=50, verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='fertilize_every',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='fertilize every'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_fertilize',
            field=models.DateField(default=datetime.date.today, verbose_name='last fertilized'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_water',
            field=models.DateField(default=datetime.date.today, verbose_name='last watered'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='manager.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(blank=True, upload_to='media/plant_pics', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_every',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='water every'),
        ),
    ]
