# Generated by Django 3.0.3 on 2020-03-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('manager', '0004_auto_20200318_2047'),
        ('accounts', '0002_auto_20200317_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
